### ISSUE TITLE
Devise locale setup missing

### ISSUE THREAD

**Issue by AAlvAAro** [panacea-rails/panacea#5]
When devise is enabled, it won't setup the translations for the locale selected.

**Comment by efigarolam** [comment]
You're right we totally missed that feature.

**Comment by memoxmrdl** [comment]
I'm working about it

**Comment by memoxmrdl** [comment]
@efigarolam too is it neccessary to translate views?

**Comment by memoxmrdl** [comment]
We will use `devise-i18n` for this, it permits to add the custom translation by default locale and to convert the devise views

**Comment by efigarolam** [comment]
Issue was solved by commit: [c8012eaa396254935fc95cdab28d074e87e40458](https://github.com/panacea-rails/panacea/commit/c8012eaa396254935fc95cdab28d074e87e40458)
